blank_issues_enabled: false
contact_links:
  - name: 📚 Development Documentation
    url: /docs/how-to-develop.md
    about: Learn how to set up and develop the Mergington High School activities system
  - name: 💬 General Questions
    url: https://github.com/switchboxeric/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss ideas with the community